name: Choice
on:
  workflow_dispatch:
    inputs:
      log-lelvel :
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  run: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.log-lelvel}}"