name: Matrix
on: push
jobs:
  print:
    strategy: # マトリックスの定義
      os: [ubuntu-latest, windows-latest, macos-latest] # osプロパティの定義
  runs-os: ${{ matrix.os }} # マトリックスの値を利用
  steps:
    - run: echo "${RUNNES_OS}"
      shell: bash