name: Secrets scan
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "${pwd}:${pwd}" -w "${pwd}" \
            secretlint/secretlint secretlint --maskSecrets '**/*'