name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD_TEST: ${{ secrets.PASSWORD_TEST }} # Secretsの参照
    steps:
      - run: echo "${PASSWORD_TEST}" # ログ出力はマスクされる
      - run: echo "${PASSWORD_TEST:0:1} ${PASSWORD_TEST#?}" # ログ出力はマスクされない