name: Prevent security misconfigurations
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: auqasecurity/trivy-action@0.19.0
        with:
          scan-type: config
          severity: CRITICAL,HIGH
          exit-code: 1